### PR TITLE
Replace google feed module with Yahoo Query Language

### PR DESCRIPTION
**Pull request by DMDc0de**
Since the google feed api stopped working, I made a quick-and-dirty edit to use YUI and yql, what do you think?

### CODE REVIEW

**Comment by siddii** [comment]
Nice... I'll take a look!

**Comment by siddii** [comment]
Thanks @DMDc0de for knocking this off! 

Very much appreciate it 👍

**Comment by DMDc0de** [comment]
My pleasure. Of course can be improved, let me know if I can help you!

**Comment by siddii** [comment]
Have some major improvements in mind for the next version. I was holding off due to Google Feeds being retiring.

Would you be willing to be a code collaborator on this repo?

**Comment by DMDc0de** [comment]
If I can be helpful, sure!

**Pull request merged**
